// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIGv4.Models;

#nullable disable

namespace PIGv4.Migrations
{
    [DbContext(typeof(PigContext))]
    partial class PigContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("PIGv4.Models.Config", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogFile")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayListDirectory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigId");

                    b.ToTable("Config");
                });

            modelBuilder.Entity("PIGv4.Models.ImportError", b =>
                {
                    b.Property<long>("ImportErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ImportErrorId");

                    b.ToTable("ImportError");
                });

            modelBuilder.Entity("PIGv4.Models.Log", b =>
                {
                    b.Property<long>("LogIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LogIdentifier");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("PIGv4.Models.MP3Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenreName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("GenreId");

                    b.ToTable("MP3Genre");
                });

            modelBuilder.Entity("PIGv4.Models.Playlist", b =>
                {
                    b.Property<int>("PlaylistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EndYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PlaylistId");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("PIGv4.Models.Song", b =>
                {
                    b.Property<int>("SongId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Album")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BPM")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileAddress")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FileDate")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Folder")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongId");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("PIGv4.Models.SongFilter", b =>
                {
                    b.Property<int>("SongFilterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("Editor")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("HasArtist")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasGenre")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("HasTitle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SongId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SongFilterId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("SongFilter");
                });

            modelBuilder.Entity("PIGv4.Models.SongFilter", b =>
                {
                    b.HasOne("PIGv4.Models.Playlist", "Playlist")
                        .WithMany("Songs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SongFilter_Playlist");

                    b.HasOne("PIGv4.Models.Song", "Song")
                        .WithMany("SongFilters")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SongFilter_Song");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("PIGv4.Models.Playlist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("PIGv4.Models.Song", b =>
                {
                    b.Navigation("SongFilters");
                });
#pragma warning restore 612, 618
        }
    }
}
